version: "3.9"

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: coink-api-dev
    working_dir: /app
    command:
      [
        "dotnet",
        "watch",
        "--project",
        "/app/src/CoinkApiDC.Api/CoinkApiDC.Api.csproj",
        "run",
        "--urls",
        "http://0.0.0.0:8080"
      ]
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: coink-api-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: coinkdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: coink-api-redis
    ports:
      - "6379:6379"
